import type { Lead } from '@/types/lead';

export const dummyLeads: Lead[] = [
  {
    id: '1', user_id: 'dummy_user_001', campaign_id: 'c1', platform: 'reddit',
    post_id: 'r1', post_url: 'https://reddit.com/r/SaaS/comments/abc123',
    post_title: 'Looking for a good CRM for my small agency — tired of HubSpot pricing',
    post_body: 'We are a 5-person digital marketing agency. HubSpot is way too expensive. Need something that tracks deals and sends follow-up emails automatically. Budget around ₹2000/month.',
    author_username: 'agencyfounder99', subreddit: 'SaaS',
    intent_score: 91, intent_level: 'high',
    matched_keywords: ['CRM', 'HubSpot alternative', 'small agency'],
    ai_summary: 'Actively shopping for a CRM, specific budget mentioned, frustrated with current solution.',
    status: 'new', is_competitor: true, competitor_name: 'HubSpot',
    detected_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    posted_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2', user_id: 'dummy_user_001', campaign_id: 'c1', platform: 'reddit',
    post_id: 'r2', post_url: 'https://reddit.com/r/entrepreneur/comments/def456',
    post_title: 'Best tools to find leads from social media? Tried everything.',
    post_body: 'Running a B2B SaaS startup. We need a way to monitor Reddit and Twitter for people asking about our problem space. Manual searches take too long.',
    author_username: 'b2bsaasfounder', subreddit: 'entrepreneur',
    intent_score: 85, intent_level: 'high',
    matched_keywords: ['lead generation', 'social media monitoring', 'B2B SaaS'],
    ai_summary: 'High-intent buyer searching for lead generation tooling for their SaaS.',
    status: 'viewed', is_competitor: false,
    detected_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    posted_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3', user_id: 'dummy_user_001', campaign_id: 'c2', platform: 'reddit',
    post_id: 'r3', post_url: 'https://reddit.com/r/smallbusiness/comments/ghi789',
    post_title: 'Does anyone use Reddit to generate leads for their business?',
    post_body: 'Wondering if Reddit can be used for B2B lead generation. Our software helps e-commerce brands with inventory management.',
    author_username: 'ecommerce_ops', subreddit: 'smallbusiness',
    intent_score: 72, intent_level: 'medium',
    matched_keywords: ['lead generation', 'Reddit marketing'],
    ai_summary: 'Exploring Reddit outbound — medium intent, could be a future buyer.',
    status: 'replied', is_competitor: false,
    ai_reply: 'Great question! Reddit is one of the most underrated lead gen channels for B2B. With LeadPulse, you can automate this entire process...',
    detected_at: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    posted_at: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4', user_id: 'dummy_user_001', campaign_id: 'c1', platform: 'reddit',
    post_id: 'r4', post_url: 'https://reddit.com/r/startups/comments/jkl012',
    post_title: 'Outbound vs inbound for early-stage B2B — what actually works?',
    post_body: 'We have tried cold email (terrible open rates), LinkedIn (expensive), and some SEO content. Need something that finds buyers who are already in the market.',
    author_username: 'earlystage_cto', subreddit: 'startups',
    intent_score: 88, intent_level: 'high',
    matched_keywords: ['outbound sales', 'B2B leads', 'cold email alternative'],
    ai_summary: 'Actively looking for outbound alternatives — very high fit for LeadPulse.',
    status: 'new', is_competitor: false,
    detected_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    posted_at: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5', user_id: 'dummy_user_001', campaign_id: 'c2', platform: 'reddit',
    post_id: 'r5', post_url: 'https://reddit.com/r/marketing/comments/mno345',
    post_title: 'Comparing Apollo vs LeadIQ vs Lusha for prospecting — any Reddit users?',
    post_body: 'We use Apollo currently but looking at alternatives. Need better intent data, not just contact data.',
    author_username: 'sales_ops_lead', subreddit: 'marketing',
    intent_score: 79, intent_level: 'high',
    matched_keywords: ['Apollo alternative', 'intent data', 'prospecting tools'],
    ai_summary: 'Competitor-aware prospect evaluating intent data tools — high conversion potential.',
    status: 'new', is_competitor: true, competitor_name: 'Apollo',
    detected_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    posted_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
];

export const dummyCampaigns = [
  {
    id: 'c1', user_id: 'dummy_user_001',
    name: 'B2B SaaS Buyers',
    description: 'People looking for SaaS tools, CRMs, and lead generation software',
    keywords: ['CRM', 'lead generation', 'B2B SaaS', 'HubSpot alternative', 'cold email alternative'],
    platforms: ['reddit'],
    subreddits: ['SaaS', 'entrepreneur', 'startups', 'marketing'],
    is_active: true,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c2', user_id: 'dummy_user_001',
    name: 'Reddit Outbound Research',
    description: 'Founders exploring Reddit as a lead gen channel',
    keywords: ['Reddit marketing', 'social media monitoring', 'outbound sales'],
    platforms: ['reddit'],
    subreddits: ['smallbusiness', 'marketing', 'growmybusiness'],
    is_active: true,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const dummyStats = {
  totalLeads: 147,
  highIntent: 63,
  replied: 28,
  campaigns: 2,
  redditLeads: 147,
  twitterLeads: 0,
  competitorMentions: 19,
  topKeywords: [
    { keyword: 'CRM', count: 34 },
    { keyword: 'lead generation', count: 28 },
    { keyword: 'B2B SaaS', count: 21 },
    { keyword: 'HubSpot alternative', count: 18 },
    { keyword: 'cold email alternative', count: 15 },
    { keyword: 'outbound sales', count: 12 },
  ],
};
