export const env = {
  supabaseUrl: process.env.NEXT_PUBLIC_SUPABASE_URL!,
  supabaseAnonKey: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
  supabaseServiceKey: process.env.SUPABASE_SERVICE_ROLE_KEY!,
  clerkSecretKey: process.env.CLERK_SECRET_KEY!,
  clerkWebhookSecret: process.env.CLERK_WEBHOOK_SECRET!,
  openaiApiKey: process.env.OPENAI_API_KEY!,
  resendApiKey: process.env.RESEND_API_KEY!,
  resendFromEmail: process.env.RESEND_FROM_EMAIL ?? 'alerts@leadpulse.io',
  payuMerchantKey: process.env.PAYU_MERCHANT_KEY!,
  payuMerchantSalt: process.env.PAYU_MERCHANT_SALT!,
  payuBaseUrl: process.env.PAYU_BASE_URL ?? 'https://secure.payu.in/_payment',
  redditClientId: process.env.REDDIT_CLIENT_ID!,
  redditClientSecret: process.env.REDDIT_CLIENT_SECRET!,
  redditUserAgent: process.env.REDDIT_USER_AGENT ?? 'LeadPulse/1.0',
  twitterBearerToken: process.env.TWITTER_BEARER_TOKEN!,
  cronSecret: process.env.CRON_SECRET!,
  appUrl: process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000',
};
